#!/usr/bin/env bash
set -o errexit

USAGE_MSG="Usage: $(basename $0) [ACTION, [ARGS...]]"
HELP_MSG="Work with note files."

# Find important 
export QUICKNOTE_NAME=$0
export QUICKNOTE=$(readlink -f $QUICKNOTE_NAME)
export QUICKNOTE_DIR=$(dirname $QUICKNOTE)

# Source library
source $QUICKNOTE_DIR/lib.sh

# Master Help
if [ -n "$ECHO_HELP" ] && [ -z $1 ]; then
    echo $USAGE_MSG
    echo $HELP_MSG
    ECHO_HELP=""
    for action in $($QUICKNOTE actions); do
        $QUICKNOTE help $action
    done
    exit 0
fi

# Source configuration files
source $QUICKNOTE_DIR/config.sh

export QUICKNOTE_USR_CFG=$HOME/.quicknote.cfg
[ -f $QUICKNOTE_USR_CFG ] && source $QUICKNOTE_USR_CFG

# Parse args
action=${1-$DEFAULT_ACTION}
shift || True

ACTION_EXE=$(get_action $action)
$ACTION_EXE $*
