#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) [ACTION, [ARGS...]]"
HELP_MSG="Work with note files."

# Find important 
export QN_NAME=$0
export QUICKNOTE=$(readlink -f $QN_NAME)
export QN_DIR=$(dirname $QUICKNOTE)

# Source library
source $QN_DIR/lib.sh

# Source default configuration file
source $QN_DIR/quicknote.cfg

# Source local configuration file
[ -f "$QN_USR_CFG" ] && source $QN_USR_CFG

# Parse args
action=${1-$QN_DEFAULT_ACTION}
shift || True

if [ "$action" = "help" ]; then
    # By contract, any actions run should just print help and exit.
    export ECHO_HELP=1
    if [ -z $1 ]; then
        echo "usage: $USAGE_MSG"
        echo $HELP_MSG
        # Execute all actions in arguments.
        for act in $(list_actions); do
            $act
        done
    exit 0
    fi
    action=$1
    shift
fi

ACTION_EXE=$(get_action $action)
if [ -z "$ACTION_EXE" ]; then
    exit 1
else
    $ACTION_EXE "$@"
fi
