#!/usr/bin/env bash
set -o errexit

USAGE_MSG="Usage: $(basename $0) [ACTION, [ARGS...]]"
HELP_MSG="Work with note files."

# Find important 
export QUICKNOTE_NAME=$0
export QUICKNOTE=$(readlink -f $QUICKNOTE_NAME)
export QUICKNOTE_DIR=$(dirname $QUICKNOTE)

# Source library
source $QUICKNOTE_DIR/lib.sh

# Source default configuration file
source $QUICKNOTE_DIR/quicknote.cfg

# Source local configuration file
export QUICKNOTE_USR_CFG=$HOME/.quicknote.cfg
[ -f $QUICKNOTE_USR_CFG ] && source $QUICKNOTE_USR_CFG

# Parse args
action=${1-$DEFAULT_ACTION}
shift || True

if [ "$action" = "help" ]; then
    # By contract, any actions run should just print help and exit.
    export ECHO_HELP=1
    if [ -z $1 ]; then
        echo $USAGE_MSG
        echo $HELP_MSG
        # Execute all actions in arguments.
        for act in $(list_actions); do
            $act
        done
    exit 0
    fi
    action=$1
    shift
fi

ACTION_EXE=$(get_action $action)
$ACTION_EXE "$@"
