#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) [NOTE]"
HELP_MSG="List archived notes.  With an arg, archive that note."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

if [ -z $1 ]; then
    set -f
    find $QN_NOTE_DIR -name *.$QN_EXT~
    set +f
elif ! [ -z $2 ]; then
    echo >&2 "Too many arguments."
    echo >&2 "usage: $(basename $QUICKNOTE) $USAGE_MSG"
else
    note=$(find_note $1)
    $QUICKNOTE git mv $note $note~
    $QUICKNOTE git commit -m "Archive $(note_root $note)"
fi

