#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0)"
HELP_MSG="Bootstrap a quicknote system."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

mkdir -p $QN_NOTE_DIR
$QUICKNOTE git init
cat > $QN_NOTE_DIR/.gitignore <<EOF
*
!*.$QN_EXT
!*.$QN_EXT~
!.git*
EOF
$QUICKNOTE git add .gitignore
$QUICKNOTE git commit -m "Initial commit"
