#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) NOTE"
HELP_MSG="Echo the contents of NOTE to stdout."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

if [ -z $1 ]; then
    echo >&2 "Insufficient arguments."
    echo >&2 "usage: $(basename $QUICKNOTE) $USAGE_MSG"
    exit 1
elif ! [ -z $2 ]; then
    echo >&2 "Too many arguments."
    echo >&2 "usage: $(basename $QUICKNOTE) $USAGE_MSG"
    exit 1
fi


note=$(find_note $1)
cat $note
