#!/usr/bin/env bash

USAGE_MSG="$(basename $0) [NOTE, [NOTE, [...]]]"
HELP_MSG="Remove empty note files.  Without arguments removes ALL empty notes."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

for note in $(list_empty "$@"); do
    $QUICKNOTE rm $note
done
