#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) [NOTE, [NOTE, [...]]]"
HELP_MSG="Remove note files if empty. Without arguments remove ALL empty notes."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

for note in $(list_empty "$@"); do
    $QUICKNOTE rm $(note_root $note)
done
