#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) NOTE"
HELP_MSG="Copy contents of NOTE to clipboard.  Clipboard program set with \$CLIPBOARD"
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

$QUICKNOTE cat "$@" | $CLIPBOARD
