#!/usr/bin/env bash

[ -d $NOTE_DIR ] || echo "$NOTE_DIR doesn't exist" >&2
cd $NOTE_DIR

git status 2>&1 >/dev/null || echo "$NOTE_DIR is not a git repository." >&2
[ -z "$(git status --porcelain)" ] || echo "$NOTE_DIR has untracked content." >&2
git diff --exit-code 2>&1 >/dev/null || echo "$NOTE_DIR has unstaged changes." >&2
git diff --staged --exit-code 2>&1 >/dev/null || echo "$NOTE_DIR has uncommitted changes." >&2
