#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0)"
HELP_MSG="Confirm that everything is right with the world."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

[ -d $QN_NOTE_DIR ] || echo >&2 "$QN_NOTE_DIR doesn't exist"
cd $QN_NOTE_DIR

git status 2>&1 >/dev/null || \
    echo >&2 "$QN_NOTE_DIR is not a git repository."
[ -z "$(git status --porcelain)" ] || \
    echo >&2 "$QN_NOTE_DIR has untracked content."
git diff --exit-code 2>&1 >/dev/null || \
    echo >&2 "$QN_NOTE_DIR has unstaged changes."
git diff --staged --exit-code 2>&1 >/dev/null || \
    echo >&2 "$QN_NOTE_DIR has uncommitted changes."
[ -z "$(git diff origin)" ] || \
    echo >&2 "$QN_NOTE_DIR is not synced with origin."
