#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) [NOTE]"
HELP_MSG="Edit NOTE.  Without argument, edit top note (see list command)."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

if [ -z $1 ]; then
    name=$(list_infos | awk 'NR==1{print $1}')
    note=$(find_note $name)
elif ! [ -z $2 ]; then
    echo >&2 "Too many arguments."
    echo >&2 "usage: $(basename $QUICKNOTE) $USAGE_MSG"
    exit 1
else
    note=$(find_note $1)
fi

$EDITOR $note

if ! $QUICKNOTE git diff --quiet --exit-code $note; then
    $QUICKNOTE git commit -m "Edit $(note_root $note)" $note
fi
