#!/usr/bin/env bash

USAGE_MSG="$(basename $0) [ARGS]"
HELP_MSG="Run git from inside \$QN_NOTE_DIR"
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

cd $QN_NOTE_DIR
git "$@"
