#!/usr/bin/env bash

USAGE_MSG="$(basename $0) [ARGS]"
HELP_MSG="Run git from inside the note directory."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

cd $NOTE_DIR
git "$@"
