#!/usr/bin/env bash

USAGE_MSG="$(basename $0) [PATTERN]"
HELP_MSG="Search notes for PATTERN."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

for file in $(list_matching "$@"); do
    echo [$(basename $file)]
    echo \# `note_title $file` \#
    grep -n --color=auto --ignore-case --no-filename "$*" $file
done
