#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) [TERM]"
HELP_MSG="List notes and their info.  With argument, list notes which match TERM."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

list_matching_infos "$@" | column -s '	' -t
