#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) NOTE DEST"
HELP_MSG="Change note file names."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

if [ -z $2 ]; then
    echo "Too few arguments."  >&2
    echo "$USAGE_MSG"          >&2
elif ! [ -z $3 ]; then
    echo "Too many arguments." >&2
    echo "$USAGE_MSG"          >&2
else
    src=$(find_note $1)
    dst=$(get_note $2)
fi

$QUICKNOTE git mv $src $dst
$QUICKNOTE git commit -m "Rename $(note_root $src) to $(note_root $dst)"
