#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) [NOTE]"
HELP_MSG="Start a new note.  If NOTE given, use that as filename."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

if ! [ -z $2 ]; then
    echo >&2 "Too many arguments."
    echo >&2 "usage: $(basename $QUICKNOTE) $USAGE_MSG"
    exit 1
fi

note=$(get_new_note $1)
$QUICKNOTE edit $(note_root $note)

# Remove if still empty
empty_note=$(list_empty $note)
if ! [ -z $empty_note ]; then
    rm -f $empty_note
else
    $QUICKNOTE git add $note
    $QUICKNOTE git commit -m "Create $(note_root $note)"
fi
