#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0)"
HELP_MSG="\$QUICKNOTE git push"
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

$QUICKNOTE git push
