#!/usr/bin/env bash
set -o errexit

USAGE_MSG="$(basename $0) NOTE, [NOTE, [...]]"
HELP_MSG="Remove note files."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

for name in "$@"; do
    note=$(find_note $name)
    rm -i $note && $QUICKNOTE git commit -m "Remove $(note_root $note)" $note
done
