#!/usr/bin/env bash

USAGE_MSG="$(basename $0) NOTE, [NOTE, [...]]"
HELP_MSG="Remove note files."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

for note in $*; do
    rm $(get_note $note)
done
